services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
      - backend_node_modules:/var/www/html/node_modules
    command: sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    working_dir: /app
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "corepack enable pnpm && pnpm install --config.allow-build=* && pnpm exec next dev --turbopack --hostname 0.0.0.0 --port 3000"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  backend_vendor:
  backend_node_modules:
  frontend_node_modules:
  mysql_data:
